diff --git a/Makefile b/Makefile
index 9e35134..b034c8d 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,7 @@ $(T)/%.tex: %.tex | src
 
 src:
 	if [ ! -d $(SRC) ]; then \
-		git clone git@github.com:mit-pdos/xv6-riscv.git $(SRC) ; \
+		git clone https://github.com/mit-pdos/xv6-riscv.git $(SRC) ; \
 	else \
 		git -C $(SRC) pull ; \
 	fi; \
